
apiVersion: v1
kind: Service
metadata:
  name: hello-to-all
  labels:
    created-by: greetings-controller
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    app: hello-to-all
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-to-all
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-to-all
  template:
    metadata:
      labels:
        app: hello-to-all
    spec:
      containers:
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:1.10
        env:
        - name: MESSAGE
          value: Hello to all!